#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config top_padding 33
bspc config bottom_padding 4
bspc config left_padding 4
bspc config right_padding 4

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


#### pywal colors
wal -i "${HOME}/.config/wal/pics/image.png" -n 
. "${HOME}/.cache/wal/colors.sh"


bspc config normal_border_color "$color15"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
bspc config presel_feedback_color "$color1"

# Set the border colors.
# feh background
feh --bg-scale "${HOME}/.config/feh/backgrounds/sun.png"

#### polybar
. "${HOME}/.config/polybar/launch.sh"
